### ISSUE TITLE
Subbject not read correctly from CSR ?

### ISSUE THREAD

**Issue by djzort** [boxbackup/boxbackup#18]
I am consistently getting this eror:
`No subject found in CSR backup01-csr.pem at /usr/bin/bbstored-certs line 297.`

I found the following from the CSR

```
# openssl req -text -in bbstored/backup01-csr.pem | grep Subject | grep CN
Subject: CN = backup01
```

It seems the spaces around the equals are a problem, i made the following change on line 291 of /usr/bin/bbstored-certs

`$subject = $1 if m/Subject:.+?CN\s?=\s?([-\.\w]+)/`

FYI
```
# cat /etc/debian_version 
9.0

# openssl version
OpenSSL 1.1.0f  25 May 2017

# dpkg -l boxbackup-server  | grep ii
ii  boxbackup-server 0.11.1~r2837-4 amd64        server for the BoxBackup remote backup system

```

**Comment by qris** [comment]
Hi @djzort,

Thanks for the bug report! I am willing to make this change, I am downloading OpenSSL 1.1.0 to try to reproduce the issue. I hope that your boxbackup is built against OpenSSL 1.0 and not 1.1, because Debian had a bad port to OpenSSL 1.1 which didn't work properly (maybe still does) and the vanilla distribution still requires 1.0.

I also notice that your certificate's common name doesn't follow the same format as the ones usually created by `bbstored-certs`. Did you create this certificate without using `bbstored-certs`? I think it would need a hyphen between BACKUP and the account name, otherwise it will fail elsewhere too.

Thanks, Chris.

**Comment by djzort** [comment]
I am using debians boxbackup package as listed in the original ticket. I also used its `dpkg-reconfigure -plow boxbackup-client` function to generate the client csr
